---
- include: ssh.yaml
- include: ntp.yaml

- name: modulefiles package
  yum:
    name: "lmod-ohpc"
    state: present

- name: mountain timezone
  timezone:
    name: America/Denver

- name: libsemanage-python package
  yum:
    name: libsemanage-python
    state: present

- name: git package
  yum:
    name: "git"
    state: present

- name: hosts file
  copy: src=etc/hosts dest=/etc/hosts

- name: user namespace sysctl
  copy: src=etc/sysctl.d/usernamespaces.conf dest=/etc/sysctl.d/usernamespaces.conf

- name: add user1
  user:
    name: user1
    uid: 1051
    password: "{{ 'user1' | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create

- name: add user2
  user:
    name: user2
    uid: 1052
    password: "{{ 'user2' | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create
